FROM python:3.8.13-alpine3.16

RUN mkdir /app && mkdir /app/frontend
ADD requirements.txt /app
WORKDIR /app

RUN set -ex \
    && apk add --no-cache --virtual .build-deps postgresql-dev build-base libffi libffi-dev build-base python3-dev py-pip jpeg-dev zlib-dev \
    && python -m venv /env \
    && /env/bin/pip install --upgrade pip \
    && /env/bin/pip install --no-cache-dir -r /app/requirements.txt